In [1]:
import numpy as np
import pulp as pl

In [2]:
# question 1
c_B = np.array([2, 3]).reshape((-1, 1))
c_N = np.array([0, 0, 0]).reshape((-1, 1))

A_B = np.array([
    [1, 1],
    [1, 2],
])
A_N = np.array([
    [1, 1, 0],
    [0, 0, 1],
])

c_B.T @ np.linalg.inv(A_B) @ A_N - c_N.T

array([[1., 1., 1.]])

In [3]:
# question 2
c_j = 4
A_j = np.array([-1, -2]).reshape((-1, 1))
c_B.T @ np.linalg.inv(A_B) @ A_j - c_j

array([[-7.]])

In [4]:
# question 3
model = pl.LpProblem(name="quiz", sense=pl.LpMaximize)

x_1 = pl.LpVariable(name="x_1", lowBound=0)
x_2 = pl.LpVariable(name="x_2", lowBound=0)
x_3 = pl.LpVariable(name="x_3", lowBound=0)

model += 2 * x_1 + 3 * x_2
model += (x_1 + x_2 + x_3 <= 4, "constraint_1")
model += (x_1 + 2 * x_2 + x_3 <= 4, "constraint_2")

status = model.solve()
if status == 1:
    for x in model.variables():
        print(x.value())

Welcome to the CBC MILP Solver 
Version: 2.10.3 
Build Date: Dec 15 2019 

command line - /Users/changyaochen/venvs/Coursera-operation-research-3-ONthjc7U/lib/python3.7/site-packages/pulp/apis/../solverdir/cbc/osx/64/cbc /var/folders/x0/qqz15_vj7m74jt8xgl51279h0000gp/T/fccc09c9e08a4224944b705d7297cd0a-pulp.mps max branch printingOptions all solution /var/folders/x0/qqz15_vj7m74jt8xgl51279h0000gp/T/fccc09c9e08a4224944b705d7297cd0a-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 7 COLUMNS
At line 16 RHS
At line 19 BOUNDS
At line 20 ENDATA
Problem MODEL has 2 rows, 3 columns and 6 elements
Coin0008I MODEL read with 0 errors
Presolve 2 (0) rows, 2 (-1) columns and 4 (-2) elements
0  Obj -0 Dual inf 4.999998 (2)
1  Obj 8
Optimal - objective value 8
After Postsolve, objective 8, infeasibilities - dual 0 (0), primal 0 (0)
Optimal objective 8 - 1 iterations time 0.002, Presolve 0.00
Option for printingOptions changed from normal to all
Total time (CPU seconds

In [5]:
b = np.array([4, 6, 1]).reshape((-1, 1))

c_B = np.array([2, 3, 0]).reshape((-1, 1))
c_N = np.array([1, 0, 0]).reshape((-1, 1))

A_B = np.array([
    [1, 1, 0],
    [1, 2, 0],
    [0, 1, 1],
])
A_N = np.array([
    [1, 1, 0],
    [0, 0, 1],
    [1, 0, 0],
])

np.linalg.inv(A_B) @ b

array([[ 2.],
       [ 2.],
       [-1.]])

In [6]:
# question 4
np.linalg.inv(A_B) @ A_N 

array([[ 2.,  2., -1.],
       [-1., -1.,  1.],
       [ 2.,  1., -1.]])